version: "3.8"
services:
  backend:
    build: ./back-end
    ports:
      - "8080:8080"
    volumes:
      - ./back-end:/app
      - /app/node_modules
  frontend:
    build: ./front-end
    ports:
      - "3000:3000"
    volumes:
      - ./front-end/src:/app/src
  # volumes:
  #   database:
  #     driver: local